import type { ArchiveFormat } from "@loomark/core/archive"
import type { CollectionKind } from "@loomark/core/types"

export type DemoCollectionSeed = {
  id: string
  name: string
  icon: string | null
  kind: CollectionKind
  parentId: string | null
  position: number
  shareToken: string | null
}

export type DemoArchiveSeed = { format: ArchiveFormat; bytes: number }

export type DemoBookmarkSeed = {
  id: string
  collectionId: string
  url: string
  title: string
  description: string | null
  faviconUrl: string | null
  previewUrl: string | null
  pinned: boolean
  position: number
  pinnedPosition: number
  daysAgo: number
  archives: DemoArchiveSeed[]
}

export const DEMO_COLLECTIONS: DemoCollectionSeed[] = [
  {
    id: "c-engineering",
    name: "Engineering",
    icon: "code",
    kind: "USER",
    parentId: null,
    position: 0,
    shareToken: null,
  },
  {
    id: "c-frontend",
    name: "Frontend",
    icon: "layout-panel-left",
    kind: "USER",
    parentId: "c-engineering",
    position: 0,
    shareToken: null,
  },
  {
    id: "c-backend",
    name: "Backend & infra",
    icon: "server",
    kind: "USER",
    parentId: "c-engineering",
    position: 1,
    shareToken: null,
  },
  {
    id: "c-ai",
    name: "AI & LLMs",
    icon: "sparkles",
    kind: "USER",
    parentId: "c-engineering",
    position: 2,
    shareToken: null,
  },
  {
    id: "c-design",
    name: "Design",
    icon: "palette",
    kind: "USER",
    parentId: null,
    position: 1,
    shareToken: "demo1c020h",
  },
  {
    id: "c-type",
    name: "Type & colour",
    icon: "type",
    kind: "USER",
    parentId: "c-design",
    position: 0,
    shareToken: null,
  },
  {
    id: "c-inspiration",
    name: "Inspiration",
    icon: "lightbulb",
    kind: "USER",
    parentId: "c-design",
    position: 1,
    shareToken: null,
  },
  {
    id: "c-reading",
    name: "Reading",
    icon: "book-open",
    kind: "USER",
    parentId: null,
    position: 2,
    shareToken: null,
  },
  {
    id: "c-essays",
    name: "Essays",
    icon: "feather",
    kind: "USER",
    parentId: "c-reading",
    position: 0,
    shareToken: null,
  },
  {
    id: "c-newsletters",
    name: "Newsletters",
    icon: "mail",
    kind: "USER",
    parentId: "c-reading",
    position: 1,
    shareToken: null,
  },
  {
    id: "c-tools",
    name: "Tools",
    icon: "wrench",
    kind: "USER",
    parentId: null,
    position: 3,
    shareToken: null,
  },
  {
    id: "c-learning",
    name: "Learning",
    icon: "graduation-cap",
    kind: "USER",
    parentId: null,
    position: 4,
    shareToken: null,
  },
  {
    id: "c-selfhost",
    name: "Self-hosting",
    icon: "hard-drive",
    kind: "USER",
    parentId: null,
    position: 5,
    shareToken: "demoad84vz",
  },
  {
    id: "c-unsorted",
    name: "Unsorted",
    icon: null,
    kind: "UNSORTED",
    parentId: null,
    position: 0,
    shareToken: null,
  },
]

export const DEMO_BOOKMARKS: DemoBookmarkSeed[] = [
  {
    id: "b-react-dev",
    collectionId: "c-frontend",
    url: "https://react.dev",
    title: "React",
    description: "React is the library for web and native user interfaces. Build user interfaces out of individual pieces called components written in JavaScript. React is designed to l…",
    faviconUrl: "https://react.dev/favicon-32x32.png",
    previewUrl: "https://react.dev/images/og-home.png",
    pinned: true,
    position: 0,
    pinnedPosition: 0,
    daysAgo: 3,
    archives: [{ format: "SCREENSHOT", bytes: 1171312 }, { format: "WEBPAGE", bytes: 1726119 }, { format: "MARKDOWN", bytes: 27747 }],
  },
  {
    id: "b-tailwindcss-com",
    collectionId: "c-frontend",
    url: "https://tailwindcss.com",
    title: "Tailwind CSS",
    description: "Tailwind CSS is a utility-first CSS framework for rapidly building modern websites without ever leaving your HTML.",
    faviconUrl: "https://tailwindcss.com/favicon.ico?favicon.0cgjfh1m3jfig.ico",
    previewUrl: "https://tailwindcss.com/opengraph-image.jpg?opengraph-image.0jwfhnd690..4.jpg",
    pinned: true,
    position: 1,
    pinnedPosition: 3,
    daysAgo: 10,
    archives: [],
  },
  {
    id: "b-nextjs-org",
    collectionId: "c-frontend",
    url: "https://nextjs.org",
    title: "Next.js by Vercel - The React Framework",
    description: "Next.js by Vercel is the full-stack React framework for the web.",
    faviconUrl: "https://nextjs.org/favicon.ico?favicon.38folom4sz_yx.ico",
    previewUrl: "https://h8dxkfmaphn8o0p3.public.blob.vercel-storage.com/nextjs/twitter-card.png",
    pinned: true,
    position: 2,
    pinnedPosition: 2,
    daysAgo: 17,
    archives: [{ format: "SCREENSHOT", bytes: 664516 }, { format: "WEBPAGE", bytes: 1819563 }],
  },
  {
    id: "b-developer-mozilla-org-en-us-docs-web-css",
    collectionId: "c-frontend",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    title: "CSS: Cascading Style Sheets",
    description: "Cascading Style Sheets (CSS) is a stylesheet language used to describe the presentation of a document written in HTML or XML (including XML dialects such as SVG, MathM…",
    faviconUrl: "https://developer.mozilla.org/favicon.ico",
    previewUrl: "https://developer.mozilla.org/mdn-social-image.46ac2375.png",
    pinned: false,
    position: 3,
    pinnedPosition: 0,
    daysAgo: 26,
    archives: [],
  },
  {
    id: "b-ui-shadcn-com",
    collectionId: "c-frontend",
    url: "https://ui.shadcn.com",
    title: "shadcn/ui - The Foundation for your Design System",
    description: "Composable, accessible components with thoughtful defaults. Build your own component library with code you can customize, extend, and make your own.",
    faviconUrl: "https://ui.shadcn.com/favicon-16x16.png",
    previewUrl: "https://ui.shadcn.com/og?title=The%20Foundation%20for%20your%20Design%20System&description=Composable%2C%20accessible%20components%20with%20thoughtful%20defaults.%20Build%20your%20own%20component%20library%20with%20code%20you%20can%20customize%2C%20extend%2C%20and%20make%20your%20own.",
    pinned: false,
    position: 4,
    pinnedPosition: 0,
    daysAgo: 31,
    archives: [],
  },
  {
    id: "b-vite-dev",
    collectionId: "c-frontend",
    url: "https://vite.dev",
    title: "Vite",
    description: "Next Generation Frontend Tooling",
    faviconUrl: "https://vite.dev/logo-without-border.svg",
    previewUrl: "https://vite.dev/og-image.jpg",
    pinned: false,
    position: 5,
    pinnedPosition: 0,
    daysAgo: 39,
    archives: [],
  },
  {
    id: "b-web-dev",
    collectionId: "c-frontend",
    url: "https://web.dev",
    title: "web.dev",
    description: "Panduan untuk membangun pengalaman web modern yang berfungsi di browser apa pun.",
    faviconUrl: "https://www.gstatic.com/devrel-devsite/prod/v5e941f15ff6710591bee254538202655020220785b40a3f4d932e94adb9f6037/web/images/favicon.png",
    previewUrl: "https://web.dev/images/social-wide.jpg?hl=id",
    pinned: false,
    position: 6,
    pinnedPosition: 0,
    daysAgo: 46,
    archives: [],
  },
  {
    id: "b-tanstack-com-query-latest",
    collectionId: "c-frontend",
    url: "https://tanstack.com/query/latest",
    title: "TanStack Query",
    description: "Powerful asynchronous state management, server-state utilities and data fetching. Fetch, cache, update, and wrangle all forms of async data in your TS/JS, React, Vue,…",
    faviconUrl: "https://tanstack.com/favicon-light.svg",
    previewUrl: "https://tanstack.com/api/og/query.png?v=2",
    pinned: false,
    position: 7,
    pinnedPosition: 0,
    daysAgo: 53,
    archives: [],
  },
  {
    id: "b-docs-docker-com",
    collectionId: "c-backend",
    url: "https://docs.docker.com",
    title: "Docker Docs",
    description: "Docker Documentation is the official Docker library of resources, manuals, and guides to help you containerize applications.",
    faviconUrl: "https://docs.docker.com/favicon.ico",
    previewUrl: "https://docs.docker.com/images/thumbnail.webp",
    pinned: false,
    position: 0,
    pinnedPosition: 0,
    daysAgo: 59,
    archives: [],
  },
  {
    id: "b-redis-io",
    collectionId: "c-backend",
    url: "https://redis.io",
    title: "Redis",
    description: "Developers love Redis. Unlock the full potential of the Redis database with Redis Enterprise and start building blazing fast apps.",
    faviconUrl: "https://redis.io/apple-icon.png?apple-icon.0oi7qb05iiq_i.png",
    previewUrl: "https://redis.io/_next/static/immutable/media/open-graph.2wot1rsqh2ybe.png",
    pinned: false,
    position: 1,
    pinnedPosition: 0,
    daysAgo: 69,
    archives: [],
  },
  {
    id: "b-prisma-io",
    collectionId: "c-backend",
    url: "https://www.prisma.io",
    title: "Prisma",
    description: "Prisma gives TypeScript and Node.js teams Prisma ORM, Prisma Postgres, and Prisma Compute: a type-safe ORM, managed Postgres, and Compute for deploying TypeScript apps…",
    faviconUrl: "https://www.prisma.io/favicon.ico?favicon.dac5693e.ico",
    previewUrl: "https://www.prisma.io/og.png",
    pinned: false,
    position: 2,
    pinnedPosition: 0,
    daysAgo: 72,
    archives: [],
  },
  {
    id: "b-kubernetes-io",
    collectionId: "c-backend",
    url: "https://kubernetes.io",
    title: "Kubernetes",
    description: "Kubernetes, also known as K8s, is an open source system for automating deployment, scaling, and management of containerized applications. It groups containers that mak…",
    faviconUrl: null,
    previewUrl: "https://kubernetes.io/images/kubernetes-open-graph.png",
    pinned: false,
    position: 3,
    pinnedPosition: 0,
    daysAgo: 78,
    archives: [],
  },
  {
    id: "b-fly-io",
    collectionId: "c-backend",
    url: "https://fly.io",
    title: "Computers for agents",
    description: "Sandboxes aren't enough. Give your agent a real computer and get back to building.",
    faviconUrl: "https://fly.io/phx/ui/images/favicon/favicon-595d1312b35dfe32838befdf8505515e.ico?vsn=d",
    previewUrl: "https://fly.io/phx/images/preview/og-2f7e07d1485310e79e58ef0690c9eacc.jpg?vsn=d",
    pinned: false,
    position: 4,
    pinnedPosition: 0,
    daysAgo: 90,
    archives: [],
  },
  {
    id: "b-caddyserver-com",
    collectionId: "c-backend",
    url: "https://caddyserver.com",
    title: "Caddy",
    description: "Caddy is a powerful, enterprise-ready, open source web server with automatic HTTPS written in Go",
    faviconUrl: "https://caddyserver.com/resources/images/favicon.png?v=1a6bbd7",
    previewUrl: "https://caddyserver.com/resources/images/open-graph-square.png?v=1a6bbd7",
    pinned: false,
    position: 5,
    pinnedPosition: 0,
    daysAgo: 93,
    archives: [],
  },
  {
    id: "b-litestream-io",
    collectionId: "c-backend",
    url: "https://litestream.io",
    title: "Litestream",
    description: "Litestream is an open-source, real-time streaming replication tool that lets you safely run SQLite applications on a single node.",
    faviconUrl: "https://litestream.io/favicon-32x32.png",
    previewUrl: "https://litestream.io/images/twitter-image.png",
    pinned: false,
    position: 6,
    pinnedPosition: 0,
    daysAgo: 101,
    archives: [{ format: "WEBPAGE", bytes: 1267605 }, { format: "PDF", bytes: 622406 }],
  },
  {
    id: "b-postgresql-org",
    collectionId: "c-backend",
    url: "https://www.postgresql.org",
    title: "PostgreSQL",
    description: "The world's most advanced open source database.",
    faviconUrl: "https://www.postgresql.org/favicon.ico",
    previewUrl: "https://www.postgresql.org/media/img/about/press/elephant.png",
    pinned: false,
    position: 7,
    pinnedPosition: 0,
    daysAgo: 109,
    archives: [{ format: "SCREENSHOT", bytes: 1768137 }],
  },
  {
    id: "b-anthropic-com",
    collectionId: "c-ai",
    url: "https://www.anthropic.com",
    title: "Anthropic",
    description: "Anthropic is an AI safety and research company that's working to build reliable, interpretable, and steerable AI systems.",
    faviconUrl: "https://cdn.prod.website-files.com/67ce28cfec624e2b733f8a52/681d52619fec35886a7f1a70_favicon.png",
    previewUrl: "https://cdn.prod.website-files.com/67ce28cfec624e2b733f8a52/68309ab48369f7ad9b4a40e1_open-graph.jpg",
    pinned: false,
    position: 0,
    pinnedPosition: 0,
    daysAgo: 113,
    archives: [],
  },
  {
    id: "b-huggingface-co",
    collectionId: "c-ai",
    url: "https://huggingface.co",
    title: "Hugging Face",
    description: "We’re on a journey to advance and democratize artificial intelligence through open source and open science.",
    faviconUrl: "https://huggingface.co/favicon.ico",
    previewUrl: "https://huggingface.co/front/thumbnails/v2-2.png",
    pinned: false,
    position: 1,
    pinnedPosition: 0,
    daysAgo: 124,
    archives: [],
  },
  {
    id: "b-ollama-com",
    collectionId: "c-ai",
    url: "https://ollama.com",
    title: "Ollama",
    description: "Ollama is the easiest way to automate your work using open models, while keeping your data safe.",
    faviconUrl: "https://ollama.com/public/icon-64x64.png",
    previewUrl: "https://ollama.com/public/og.png",
    pinned: false,
    position: 2,
    pinnedPosition: 0,
    daysAgo: 130,
    archives: [],
  },
  {
    id: "b-arxiv-org-abs-1706-03762",
    collectionId: "c-ai",
    url: "https://arxiv.org/abs/1706.03762",
    title: "Attention Is All You Need",
    description: "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks in an encoder-decoder configuration. The best performing mode…",
    faviconUrl: "https://arxiv.org/static/browse/0.3.4/images/icons/favicon-32x32.png",
    previewUrl: "https://arxiv.org/static/browse/0.3.4/images/arxiv-logo-fb.png",
    pinned: false,
    position: 3,
    pinnedPosition: 0,
    daysAgo: 138,
    archives: [{ format: "PDF", bytes: 604568 }, { format: "MARKDOWN", bytes: 23937 }],
  },
  {
    id: "b-karpathy-github-io",
    collectionId: "c-ai",
    url: "https://karpathy.github.io",
    title: "Andrej Karpathy blog",
    description: "Musings of a Computer Scientist.",
    faviconUrl: null,
    previewUrl: null,
    pinned: false,
    position: 4,
    pinnedPosition: 0,
    daysAgo: 144,
    archives: [],
  },
  {
    id: "b-deeplearning-ai",
    collectionId: "c-ai",
    url: "https://www.deeplearning.ai",
    title: "DeepLearning.AI",
    description: "DeepLearning.AI | Andrew Ng | Join over 7 million people learning how to use and build AI through our online courses. Earn certifications, level up your skills, and st…",
    faviconUrl: "https://www.deeplearning.ai/favicon.ico",
    previewUrl: "https://home-wordpress.deeplearning.ai/wp-content/uploads/2024/06/homepage-preview.png",
    pinned: false,
    position: 5,
    pinnedPosition: 0,
    daysAgo: 151,
    archives: [],
  },
  {
    id: "b-simonwillison-net",
    collectionId: "c-ai",
    url: "https://simonwillison.net",
    title: "Simon Willison’s Weblog",
    description: null,
    faviconUrl: "https://simonwillison.net/favicon.ico",
    previewUrl: null,
    pinned: false,
    position: 6,
    pinnedPosition: 0,
    daysAgo: 157,
    archives: [{ format: "WEBPAGE", bytes: 2108111 }, { format: "MARKDOWN", bytes: 15285 }],
  },
  {
    id: "b-figma-com",
    collectionId: "c-design",
    url: "https://www.figma.com",
    title: "Figma",
    description: "Figma is the canvas where design, code, and AI come together. From first idea to shipped product — go from concept to production with your whole team, in one place.",
    faviconUrl: "https://static.figma.com/app/icon/2/touch-76.png",
    previewUrl: "https://cdn.sanity.io/images/599r6htc/regionalized/b08d37520f7d5ad8d6562975b5932dd2d9a862bb-1200x630.gif?w=1200&q=70&fit=max&auto=format",
    pinned: true,
    position: 0,
    pinnedPosition: 5,
    daysAgo: 164,
    archives: [],
  },
  {
    id: "b-refactoringui-com",
    collectionId: "c-design",
    url: "https://refactoringui.com",
    title: "Refactoring UI",
    description: "Learn how to design awesome UIs by yourself using specific tactics explained from a developer’s point-of-view.",
    faviconUrl: "https://refactoringui.com/favicon-32x32.png",
    previewUrl: "https://refactoringui.com/img/homepage/og-image.png",
    pinned: false,
    position: 1,
    pinnedPosition: 0,
    daysAgo: 174,
    archives: [{ format: "SCREENSHOT", bytes: 1196273 }],
  },
  {
    id: "b-lawsofux-com",
    collectionId: "c-design",
    url: "https://lawsofux.com",
    title: "Laws of UX",
    description: "Laws of UX is a collection of best practices that designers can consider when building user interfaces.",
    faviconUrl: null,
    previewUrl: "https://lawsofux.com/home/social.en.png",
    pinned: false,
    position: 2,
    pinnedPosition: 0,
    daysAgo: 176,
    archives: [{ format: "SCREENSHOT", bytes: 1502340 }, { format: "WEBPAGE", bytes: 2203883 }],
  },
  {
    id: "b-oklch-com",
    collectionId: "c-type",
    url: "https://oklch.com",
    title: "OKLCH Color Picker",
    description: "OKLCH is a new way to encode colors (like hex, RGBA, or HSL)",
    faviconUrl: "https://oklch.com/favicon.ico",
    previewUrl: "https://oklch.com/og-oklch.png",
    pinned: false,
    position: 0,
    pinnedPosition: 0,
    daysAgo: 183,
    archives: [],
  },
  {
    id: "b-fontsinuse-com",
    collectionId: "c-type",
    url: "https://fontsinuse.com",
    title: "Fonts In Use",
    description: "A searchable archive of typographic design, indexed by typeface, format, and topic.",
    faviconUrl: "https://assets.fontsinuse.com/images/icons/apple-touch-icon-76x76.png",
    previewUrl: "https://cards.fontsinuse.com/cardshot?s=twitter&t=gallery&url=https://fontsinuse.com/&k=fea3b3b2f54abc640c7705b62dd465bd&v=23db1800",
    pinned: false,
    position: 1,
    pinnedPosition: 0,
    daysAgo: 191,
    archives: [],
  },
  {
    id: "b-fonts-google-com",
    collectionId: "c-type",
    url: "https://fonts.google.com",
    title: "Google Fonts",
    description: "Making the web more beautiful, fast, and open through great typography",
    faviconUrl: "https://www.gstatic.com/images/icons/material/apps/fonts/1x/catalog/v5/favicon.svg",
    previewUrl: "https://www.gstatic.com/images/icons/material/apps/fonts/1x/catalog/v5/opengraph_color.png",
    pinned: false,
    position: 2,
    pinnedPosition: 0,
    daysAgo: 197,
    archives: [],
  },
  {
    id: "b-happyhues-co",
    collectionId: "c-type",
    url: "https://www.happyhues.co",
    title: "Happy Hues",
    description: "See color palette inspiration on a real example website. As you click on different palettes every color on this site updates to give you context of how that color coul…",
    faviconUrl: "https://cdn.prod.website-files.com/5dd40aa8049df8748c72d0ee/5dd9b94105da589ba59c4907_happy-hues-fav.png",
    previewUrl: "https://cdn.prod.website-files.com/5dd40aa8049df8748c72d0ee/5ddd471cbe5e6601554a2a4d_happy-hues.jpeg",
    pinned: false,
    position: 3,
    pinnedPosition: 0,
    daysAgo: 206,
    archives: [],
  },
  {
    id: "b-coolors-co",
    collectionId: "c-type",
    url: "https://coolors.co",
    title: "Coolors",
    description: "Generate or browse beautiful color combinations for your designs.",
    faviconUrl: "https://coolors.co/assets/img/favicon.png",
    previewUrl: "https://coolors.co/assets/img/og_image.png",
    pinned: false,
    position: 4,
    pinnedPosition: 0,
    daysAgo: 214,
    archives: [],
  },
  {
    id: "b-type-scale-com",
    collectionId: "c-type",
    url: "https://type-scale.com",
    title: "Typescale",
    description: null,
    faviconUrl: "https://typescale.com/wp-content/themes/typescale/favicon/favicon-32x32.png?ver=1.2.49",
    previewUrl: "https://typescale.com/wp-content/uploads/2023/11/og-image.png",
    pinned: false,
    position: 5,
    pinnedPosition: 0,
    daysAgo: 220,
    archives: [],
  },
  {
    id: "b-dribbble-com",
    collectionId: "c-inspiration",
    url: "https://dribbble.com",
    title: "Dribbble",
    description: "Where designers get inspired — shots, portfolios and the people behind them.",
    faviconUrl: null,
    previewUrl: null,
    pinned: false,
    position: 0,
    pinnedPosition: 0,
    daysAgo: 230,
    archives: [],
  },
  {
    id: "b-mobbin-com",
    collectionId: "c-inspiration",
    url: "https://mobbin.com",
    title: "Mobbin",
    description: "Save hours of UI & UX research with our library of 400,000+ fully searchable mobile & web app screenshots.",
    faviconUrl: "https://framerusercontent.com/images/oPS7zaP2iinQmw4du221pyfo.svg",
    previewUrl: "https://framerusercontent.com/assets/FE3uqmxi41SxsiiVq9JNJC1Pwc.png",
    pinned: false,
    position: 1,
    pinnedPosition: 0,
    daysAgo: 232,
    archives: [],
  },
  {
    id: "b-land-book-com",
    collectionId: "c-inspiration",
    url: "https://land-book.com",
    title: "Land-book",
    description: "A hand-picked gallery of website designs, updated every day.",
    faviconUrl: "https://land-book.com/favicon.ico",
    previewUrl: null,
    pinned: false,
    position: 2,
    pinnedPosition: 0,
    daysAgo: 241,
    archives: [],
  },
  {
    id: "b-siteinspire-com",
    collectionId: "c-inspiration",
    url: "https://www.siteinspire.com",
    title: "SiteInspire",
    description: "A showcase of the finest web and interactive design.",
    faviconUrl: null,
    previewUrl: null,
    pinned: false,
    position: 3,
    pinnedPosition: 0,
    daysAgo: 247,
    archives: [],
  },
  {
    id: "b-godly-website",
    collectionId: "c-inspiration",
    url: "https://godly.website",
    title: "Recent — Design Inspiration",
    description: "The best design inspiration on the Internet.",
    faviconUrl: "https://recent.design/favicon.svg",
    previewUrl: "https://recent.design/og.png",
    pinned: false,
    position: 4,
    pinnedPosition: 0,
    daysAgo: 257,
    archives: [],
  },
  {
    id: "b-awwwards-com",
    collectionId: "c-inspiration",
    url: "https://www.awwwards.com",
    title: "Awwwards",
    description: "Awards for design, creativity and innovation on the internet.",
    faviconUrl: null,
    previewUrl: null,
    pinned: false,
    position: 5,
    pinnedPosition: 0,
    daysAgo: 264,
    archives: [],
  },
  {
    id: "b-longreads-com",
    collectionId: "c-reading",
    url: "https://longreads.com",
    title: "Longreads",
    description: "Sharing the best nonfiction storytelling on the web since 2011.",
    faviconUrl: "https://longreads.com/wp-content/uploads/2017/01/longreads-logo-sm-rgb-150x150.png",
    previewUrl: "https://longreads.com/wp-content/uploads/2026/08/Questionnaire-Template-JonRonson-1-1024x597.png",
    pinned: false,
    position: 0,
    pinnedPosition: 0,
    daysAgo: 267,
    archives: [],
  },
  {
    id: "b-news-ycombinator-com",
    collectionId: "c-reading",
    url: "https://news.ycombinator.com",
    title: "Hacker News",
    description: null,
    faviconUrl: "https://news.ycombinator.com/y18.svg",
    previewUrl: null,
    pinned: true,
    position: 1,
    pinnedPosition: 4,
    daysAgo: 7,
    archives: [],
  },
  {
    id: "b-danluu-com",
    collectionId: "c-essays",
    url: "https://danluu.com",
    title: "Dan Luu",
    description: null,
    faviconUrl: null,
    previewUrl: null,
    pinned: false,
    position: 0,
    pinnedPosition: 0,
    daysAgo: 13,
    archives: [{ format: "MARKDOWN", bytes: 17741 }],
  },
  {
    id: "b-paulgraham-com-greatwork-html",
    collectionId: "c-essays",
    url: "https://paulgraham.com/greatwork.html",
    title: "How to Do Great Work",
    description: null,
    faviconUrl: "http://ycombinator.com/arc/arc.png",
    previewUrl: null,
    pinned: false,
    position: 1,
    pinnedPosition: 0,
    daysAgo: 21,
    archives: [{ format: "WEBPAGE", bytes: 645766 }, { format: "MARKDOWN", bytes: 4080 }, { format: "PDF", bytes: 713303 }],
  },
  {
    id: "b-joelonsoftware-com",
    collectionId: "c-essays",
    url: "https://www.joelonsoftware.com",
    title: "Joel on Software",
    description: "A weblog by Joel Spolsky, a programmer working in New York City, about software and software companies.",
    faviconUrl: "https://i0.wp.com/www.joelonsoftware.com/wp-content/uploads/2016/12/11969842.jpg?fit=32%2C32&#038;ssl=1",
    previewUrl: "https://i0.wp.com/www.joelonsoftware.com/wp-content/uploads/2016/12/11969842.jpg?fit=400%2C400&#038;ssl=1",
    pinned: false,
    position: 2,
    pinnedPosition: 0,
    daysAgo: 29,
    archives: [],
  },
  {
    id: "b-martinfowler-com",
    collectionId: "c-essays",
    url: "https://martinfowler.com",
    title: "Martin Fowler",
    description: null,
    faviconUrl: "https://martinfowler.com/favicon.ico",
    previewUrl: null,
    pinned: false,
    position: 3,
    pinnedPosition: 0,
    daysAgo: 35,
    archives: [{ format: "SCREENSHOT", bytes: 745537 }, { format: "MARKDOWN", bytes: 30772 }],
  },
  {
    id: "b-blog-codinghorror-com",
    collectionId: "c-essays",
    url: "https://blog.codinghorror.com",
    title: "Coding Horror",
    description: "programming and human factors",
    faviconUrl: "https://storage.ghost.io/c/eb/aa/ebaa2665-01a8-4415-8825-69d1f0e8fd19/content/images/size/w256h256/2020/06/3cffc4b347c3587f19fe222caaac69f63b9a5e73.png",
    previewUrl: null,
    pinned: false,
    position: 4,
    pinnedPosition: 0,
    daysAgo: 46,
    archives: [],
  },
  {
    id: "b-jvns-ca",
    collectionId: "c-essays",
    url: "https://jvns.ca",
    title: "Julia Evans",
    description: "Julia Evans",
    faviconUrl: "https://jvns.ca/favicon.ico",
    previewUrl: null,
    pinned: false,
    position: 5,
    pinnedPosition: 0,
    daysAgo: 51,
    archives: [{ format: "MARKDOWN", bytes: 27976 }],
  },
  {
    id: "b-bytes-dev",
    collectionId: "c-newsletters",
    url: "https://bytes.dev",
    title: "Bytes",
    description: "The most entertaining (and informative) JavaScript newsletter. Delivered twice a week, for free.",
    faviconUrl: "https://bytes.dev/favicon/favicon-32x32.png",
    previewUrl: "https://bytes.dev/images/bytes-best-javascript-newsletter.png",
    pinned: false,
    position: 0,
    pinnedPosition: 0,
    daysAgo: 57,
    archives: [],
  },
  {
    id: "b-thisweekinreact-com",
    collectionId: "c-newsletters",
    url: "https://thisweekinreact.com",
    title: "This Week In React",
    description: null,
    faviconUrl: null,
    previewUrl: null,
    pinned: false,
    position: 1,
    pinnedPosition: 0,
    daysAgo: 63,
    archives: [],
  },
  {
    id: "b-newsletter-pragmaticengineer-com",
    collectionId: "c-newsletters",
    url: "https://newsletter.pragmaticengineer.com",
    title: "The Pragmatic Engineer",
    description: "Big Tech and startups, from the inside. Highly relevant for software engineers, AI engineers and engineering leaders, useful for those working in tech. Click to read T…",
    faviconUrl: "https://substackcdn.com/image/fetch/$s_!ktEI!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F47d77fcc-2914-46a1-8d39-3a6e8758e0ad%2Fapple-touch-icon-60x60.png",
    previewUrl: "https://substackcdn.com/image/fetch/$s_!8_8l!,f_auto,q_auto:best,fl_progressive:steep/https%3A%2F%2Fpragmaticengineer.substack.com%2Ftwitter%2Fsubscribe-card.jpg%3Fv%3D1600631602%26version%3D9",
    pinned: false,
    position: 2,
    pinnedPosition: 0,
    daysAgo: 70,
    archives: [],
  },
  {
    id: "b-tldr-tech",
    collectionId: "c-newsletters",
    url: "https://tldr.tech",
    title: "TLDR",
    description: "TLDR is the free daily newsletter with the most interesting stories in startups, tech and programming!",
    faviconUrl: "https://tldr.tech/favicon.ico",
    previewUrl: "https://tldr.tech/logo-jpg.jpg",
    pinned: false,
    position: 3,
    pinnedPosition: 0,
    daysAgo: 76,
    archives: [],
  },
  {
    id: "b-obsidian-md",
    collectionId: "c-tools",
    url: "https://obsidian.md",
    title: "Obsidian - Sharpen your thinking",
    description: "The free and flexible app for your private thoughts.",
    faviconUrl: "https://obsidian.md/favicon.ico",
    previewUrl: "https://obsidian.md/images/banner.png",
    pinned: true,
    position: 0,
    pinnedPosition: 8,
    daysAgo: 87,
    archives: [],
  },
  {
    id: "b-excalidraw-com",
    collectionId: "c-tools",
    url: "https://excalidraw.com",
    title: "Excalidraw",
    description: "Excalidraw is a virtual collaborative whiteboard tool that lets you easily sketch diagrams that have a hand-drawn feel to them.",
    faviconUrl: "https://excalidraw.com/favicon-32x32.png",
    previewUrl: "https://excalidraw.com/og-image-3.png",
    pinned: true,
    position: 1,
    pinnedPosition: 6,
    daysAgo: 95,
    archives: [],
  },
  {
    id: "b-github-com",
    collectionId: "c-tools",
    url: "https://github.com",
    title: "GitHub",
    description: "Join the world's most widely adopted, AI-powered developer platform where millions of developers, businesses, and the largest open source community build software that…",
    faviconUrl: "https://github.com/fluidicon.png",
    previewUrl: "https://images.ctfassets.net/8aevphvgewt8/4pe4eOtUJ0ARpZRE4fNekf/f52b1f9c52f059a33170229883731ed0/GH-Homepage-Universe-img.png",
    pinned: true,
    position: 2,
    pinnedPosition: 1,
    daysAgo: 97,
    archives: [],
  },
  {
    id: "b-raycast-com",
    collectionId: "c-tools",
    url: "https://www.raycast.com",
    title: "Raycast",
    description: "A collection of powerful productivity tools all within an extendable launcher.",
    faviconUrl: "https://www.raycast.com/favicon-production.png",
    previewUrl: "https://www.raycast.com/opengraph-image-pwu6ef.png?opengraph-image.1f-98etzkaz5s.png",
    pinned: false,
    position: 3,
    pinnedPosition: 0,
    daysAgo: 105,
    archives: [],
  },
  {
    id: "b-warp-dev",
    collectionId: "c-tools",
    url: "https://www.warp.dev",
    title: "Warp",
    description: "Infrastructure to build, measure, and interact with agents across your SDLC — so you ship more and spend less.",
    faviconUrl: "https://www.warp.dev/apple-touch-icon-60x60.png",
    previewUrl: "https://www.warp.dev/og/default.png",
    pinned: false,
    position: 4,
    pinnedPosition: 0,
    daysAgo: 111,
    archives: [],
  },
  {
    id: "b-linear-app",
    collectionId: "c-tools",
    url: "https://linear.app",
    title: "Linear",
    description: "Purpose-built for planning and building products with AI agents.",
    faviconUrl: "https://linear.app/favicon.ico?v=2",
    previewUrl: "https://linear.app/static/og/homepage.jpg",
    pinned: true,
    position: 5,
    pinnedPosition: 7,
    daysAgo: 122,
    archives: [],
  },
  {
    id: "b-httpie-io",
    collectionId: "c-tools",
    url: "https://httpie.io",
    title: "HTTPie",
    description: "Making APIs simple and intuitive for those building the tools of our time.",
    faviconUrl: "https://httpie.io/Brand/Favicons/Black/apple-icon-60x60.png",
    previewUrl: "https://httpie.io/Images/Share/default.png",
    pinned: false,
    position: 6,
    pinnedPosition: 0,
    daysAgo: 129,
    archives: [],
  },
  {
    id: "b-regex101-com",
    collectionId: "c-tools",
    url: "https://regex101.com",
    title: "regex101: build, test, and debug regex",
    description: "Online regex tester and debugger with real-time match highlighting, detailed explanations, substitutions, unit tests, benchmarking, and code generation. Supports PCRE2…",
    faviconUrl: "https://regex101.com/static/assets/icons/apple-icon-180.png",
    previewUrl: "https://regex101.com/preview/",
    pinned: false,
    position: 7,
    pinnedPosition: 0,
    daysAgo: 134,
    archives: [],
  },
  {
    id: "b-roadmap-sh",
    collectionId: "c-learning",
    url: "https://roadmap.sh",
    title: "Developer Roadmaps",
    description: "Community driven roadmaps, articles and guides for developers to grow in their career.",
    faviconUrl: "https://roadmap.sh/manifest/icon32.png",
    previewUrl: "https://roadmap.sh/img/og-img.png",
    pinned: false,
    position: 0,
    pinnedPosition: 0,
    daysAgo: 144,
    archives: [],
  },
  {
    id: "b-exercism-org",
    collectionId: "c-learning",
    url: "https://exercism.org",
    title: "Exercism",
    description: "Practice programming exercises in 70+ languages, with free mentoring.",
    faviconUrl: null,
    previewUrl: null,
    pinned: false,
    position: 1,
    pinnedPosition: 0,
    daysAgo: 148,
    archives: [],
  },
  {
    id: "b-css-tricks-com",
    collectionId: "c-learning",
    url: "https://css-tricks.com",
    title: "CSS-Tricks",
    description: "CSS-Tricks is where folks around the world come to learn about front-end code and everything related to it, including HTML, CSS, and yes, CSS.",
    faviconUrl: "https://css-tricks.com/favicon.ico",
    previewUrl: "https://i0.wp.com/css-tricks.com/wp-content/uploads/2019/12/css-tricks-logo-gradient-outline.png",
    pinned: false,
    position: 2,
    pinnedPosition: 0,
    daysAgo: 154,
    archives: [],
  },
  {
    id: "b-freecodecamp-org",
    collectionId: "c-learning",
    url: "https://www.freecodecamp.org",
    title: "freeCodeCamp.org",
    description: "Learn to Code — For Free",
    faviconUrl: "https://www.freecodecamp.org/icons/icon-72x72.png",
    previewUrl: "https://cdn.freecodecamp.org/platform/universal/fcc_meta_1920X1080-indigo.png",
    pinned: false,
    position: 3,
    pinnedPosition: 0,
    daysAgo: 161,
    archives: [],
  },
  {
    id: "b-javascript-info",
    collectionId: "c-learning",
    url: "https://javascript.info",
    title: "The Modern JavaScript Tutorial",
    description: "Modern JavaScript Tutorial: simple, but detailed explanations with examples and tasks, including: closures, document and events, object oriented programming and more.",
    faviconUrl: "https://javascript.info/img/favicon/favicon.png",
    previewUrl: "https://javascript.info/img/site_preview_en_1200x630.png",
    pinned: false,
    position: 4,
    pinnedPosition: 0,
    daysAgo: 172,
    archives: [],
  },
  {
    id: "b-frontendmasters-com",
    collectionId: "c-learning",
    url: "https://frontendmasters.com",
    title: "Frontend Masters",
    description: "Advance your web development and software engineering skills from front-end to full-stack!",
    faviconUrl: "https://master.dev/favicon.ico",
    previewUrl: "https://cdn.master.dev/assets/fm-md/med/home/md-opengraph-v1.jpg",
    pinned: false,
    position: 5,
    pinnedPosition: 0,
    daysAgo: 178,
    archives: [],
  },
  {
    id: "b-github-com-linkwarden-linkwarden",
    collectionId: "c-selfhost",
    url: "https://github.com/linkwarden/linkwarden",
    title: "linkwarden/linkwarden",
    description: "⚡️⚡️⚡️ Self-hosted collaborative bookmark manager to collect, read, annotate, and fully preserve what matters, all in one place. - linkwarden/linkwarden",
    faviconUrl: "https://github.com/fluidicon.png",
    previewUrl: "https://repository-images.githubusercontent.com/479657569/2d809ad0-9ad6-4d55-ae35-003189b1b242",
    pinned: false,
    position: 0,
    pinnedPosition: 0,
    daysAgo: 183,
    archives: [{ format: "SCREENSHOT", bytes: 1836970 }, { format: "MARKDOWN", bytes: 10327 }],
  },
  {
    id: "b-home-assistant-io",
    collectionId: "c-selfhost",
    url: "https://www.home-assistant.io",
    title: "Home Assistant",
    description: "Open source home automation that puts local control and privacy first. Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect to run on a Raspberry…",
    faviconUrl: "https://www.home-assistant.io/images/favicon.ico",
    previewUrl: "https://www.home-assistant.io/images/default-social.png",
    pinned: false,
    position: 1,
    pinnedPosition: 0,
    daysAgo: 191,
    archives: [],
  },
  {
    id: "b-umami-is",
    collectionId: "c-selfhost",
    url: "https://umami.is",
    title: "Umami – Privacy-First Analytics Platform",
    description: "Umami is the open-source, privacy-first analytics platform. Understand traffic, campaigns, behavior, conversions, and revenue — all in one place, no cookies required.",
    faviconUrl: "https://umami.is/favicon.ico",
    previewUrl: "https://umami.is/opengraph-image-j8qpfc.png?opengraph-image.061x5-78_1ett.png",
    pinned: false,
    position: 2,
    pinnedPosition: 0,
    daysAgo: 198,
    archives: [],
  },
  {
    id: "b-immich-app",
    collectionId: "c-selfhost",
    url: "https://immich.app",
    title: "Immich",
    description: "Self-hosted photo and video management solution. Easily back up, organize, and manage your photos on your own server. Immich helps you browse, search and organize your…",
    faviconUrl: "https://immich.app/favicon.ico",
    previewUrl: "https://immich.app/img/social-preview.png",
    pinned: false,
    position: 3,
    pinnedPosition: 0,
    daysAgo: 206,
    archives: [],
  },
  {
    id: "b-jellyfin-org",
    collectionId: "c-selfhost",
    url: "https://jellyfin.org",
    title: "Jellyfin",
    description: "The volunteer-built media solution that puts you in control of your media. Stream to any device from your own server, with no strings attached.",
    faviconUrl: "https://jellyfin.org/images/favicon.ico",
    previewUrl: "https://jellyfin.org/images/social.png?v2",
    pinned: false,
    position: 4,
    pinnedPosition: 0,
    daysAgo: 210,
    archives: [],
  },
  {
    id: "b-coolify-io",
    collectionId: "c-selfhost",
    url: "https://coolify.io",
    title: "Coolify",
    description: "Self-hosting platform with superpowers. Deploy apps, databases &#38; 280+ services to your server. Open-source alternative to Heroku.",
    faviconUrl: "https://coolify.io/android-launchericon-72-72.png",
    previewUrl: "https://cdn.coollabs.io/og-images/coolify.png",
    pinned: false,
    position: 5,
    pinnedPosition: 0,
    daysAgo: 221,
    archives: [],
  },
  {
    id: "b-selfh-st",
    collectionId: "c-selfhost",
    url: "https://selfh.st",
    title: "selfh.st - Self-hosted content and software",
    description: "Self-hosted news, content, updates, launches, events, and more",
    faviconUrl: "https://selfh.st/content/images/size/w256h256/2023/09/favicon-1.png",
    previewUrl: "https://selfh.st/content/images/size/w1200/2024/07/selfh-st-logo-banner-3.png",
    pinned: false,
    position: 6,
    pinnedPosition: 0,
    daysAgo: 228,
    archives: [{ format: "WEBPAGE", bytes: 2259350 }],
  },
  {
    id: "b-raspberrypi-com",
    collectionId: "c-unsorted",
    url: "https://www.raspberrypi.com",
    title: "Raspberry Pi",
    description: "Small, affordable computers for makers, learners and tinkerers.",
    faviconUrl: "https://www.raspberrypi.com/favicon.ico",
    previewUrl: null,
    pinned: false,
    position: 0,
    pinnedPosition: 0,
    daysAgo: 235,
    archives: [],
  },
  {
    id: "b-sqlite-org",
    collectionId: "c-unsorted",
    url: "https://sqlite.org",
    title: "SQLite",
    description: null,
    faviconUrl: null,
    previewUrl: null,
    pinned: false,
    position: 1,
    pinnedPosition: 0,
    daysAgo: 241,
    archives: [],
  },
  {
    id: "b-bun-sh",
    collectionId: "c-unsorted",
    url: "https://bun.sh",
    title: "Bun — A fast all-in-one JavaScript runtime",
    description: "Bundle, install, and run JavaScript & TypeScript — all in Bun. Bun is a fast JavaScript runtime & toolkit with a bundler, test runner, and npm-compatible package manag…",
    faviconUrl: "https://bun.sh/favicon.ico",
    previewUrl: "https://bun.com/share_v4.png",
    pinned: false,
    position: 2,
    pinnedPosition: 0,
    daysAgo: 246,
    archives: [],
  },
  {
    id: "b-caniuse-com",
    collectionId: "c-unsorted",
    url: "https://caniuse.com",
    title: "Can I use",
    description: "\"Can I use\" provides up-to-date browser support tables for support of front-end web technologies on desktop and mobile web browsers.",
    faviconUrl: "https://caniuse.com/img/favicon-128.png",
    previewUrl: null,
    pinned: false,
    position: 3,
    pinnedPosition: 0,
    daysAgo: 252,
    archives: [{ format: "SCREENSHOT", bytes: 698791 }],
  },
  {
    id: "b-ffmpeg-org",
    collectionId: "c-unsorted",
    url: "https://ffmpeg.org",
    title: "FFmpeg",
    description: null,
    faviconUrl: "https://ffmpeg.org/favicon.ico",
    previewUrl: null,
    pinned: false,
    position: 4,
    pinnedPosition: 0,
    daysAgo: 263,
    archives: [],
  },
]
